"""make eco requested_by nullable

Revision ID: 412844f45006
Revises: 5ea826ee46dc
Create Date: 2026-04-05 16:10:56.245313
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '412844f45006'
down_revision: Union[str, None] = '5ea826ee46dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecos', 'requested_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecos', 'requested_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
