"""make assigned_to nullable on crm_leads and capas

Revision ID: 5ea826ee46dc
Revises: f2ff847f585c
Create Date: 2026-04-05 16:07:57.741917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '5ea826ee46dc'
down_revision: Union[str, None] = 'f2ff847f585c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_activities', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('crm_leads', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_leads', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('crm_activities', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
