"""make ncr reported_by nullable

Revision ID: 5f3ae4b8d144
Revises: 412844f45006
Create Date: 2026-04-05 16:12:29.826237
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '5f3ae4b8d144'
down_revision: Union[str, None] = '412844f45006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ncrs', 'reported_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ncrs', 'reported_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
