"""make supplier contact fields nullable

Revision ID: dc94215d8839
Revises: e46130b7b277
Create Date: 2026-03-31 13:07:58.591900
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'dc94215d8839'
down_revision: Union[str, None] = 'e46130b7b277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'production_lines', 'work_orders', ['current_wo_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'sales_orders', 'crm_contacts', ['customer_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('suppliers', 'contact_person',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'contact_person',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_lines', type_='foreignkey')
    # ### end Alembic commands ###
